name: c_execution_pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Runs every hour at minute 0 (e.g., 1:00, 2:00, 3:00, etc.)
    - cron: '0 * * * *'

jobs: 
  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Show files
        run: dir

      - name: Build Hello World
        run: gcc Hello.c -o Hello.exe

      - name: Run Hello World Program
        run: .\Hello.exe

  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Show files
        run: ls -la

      - name: Build Hello World
        run: gcc Hello.c -o Hello

      - name: Run Hello World Program
        run: ./Hello
